# Generated by Django 5.0.4 on 2024-04-17 11:20

from django.db import migrations, models
from django_ckeditor_5.fields import CKEditor5Field

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(max_length=255)),
                ('courseimgurl', models.CharField(max_length=255)),
                ('coursedesc', models.CharField(max_length=255)),
                ('courseperiod', models.CharField(max_length=255)),
                ('courserate', models.CharField(max_length=255)),
                ('body',CKEditor5Field()),
            ],
        ),
    ]
