# Generated by Django 5.0.4 on 2024-04-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_course_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image_file',
            field=models.ImageField(default='path_to_default_image.jpg', upload_to='static/course_images/'),
        ),
    ]
