# Generated by Django 5.0.4 on 2024-04-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_alter_course_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image_file',
            field=models.ImageField(upload_to='course_images/'),
        ),
    ]
