# Generated by Django 5.0.4 on 2024-05-10 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0010_alter_contacts_course_alter_contacts_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='contact',
            field=models.CharField(max_length=11),
        ),
    ]
