name: Django Deployment

on:
  push:
    branches:
      - main  # Trigger deployment on pushes to the 'main' branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Replace '3.x' with your desired Python version

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Run Tests (Optional but recommended)
      - name: Run Tests
        run: |
          python manage.py test

      # 5. Build static files
      - name: Collect static files
        run: |
          python manage.py collectstatic --noinput

      # 6. Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }} # e.g., 'us-east-1'

      # 7. Deploy to AWS Elastic Beanstalk
      - name: Deploy to Elastic Beanstalk
        uses: aws-actions/aws-elastic-beanstalk-deploy@v1
        with:
          application-name: your-app-name  # Replace with your EB application name
          environment-name: your-env-name  # Replace with your EB environment name
          version-label: ${{ github.sha }}
          deployment-package: .  # Deploy the entire current directory
