name: Deploy Django to AWS Elastic Beanstalk

on:
  push:
    branches: [ main ] # Trigger on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ' 3.12.2' # Replace with your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Collect static files
      run: python manage.py collectstatic --noinput

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 # Replace with your AWS region

    - name: Deploy to Elastic Beanstalk
      uses: aws-actions/aws-elastic-beanstalk-deploy@v1
      with:
        application-name: your-app-name # Replace with your EB application name
        environment-name: your-env-name # Replace with your EB environment name
        version-label: ${{ github.sha }}
        deployment-package: ./
